### ISSUE TITLE
"ProductNotFound" When Running HiddenSectorProducer on UL MiniAOD

### ISSUE THREAD

**Issue by JHiltbrand** [TreeMaker/TreeMaker#600]
In running `TreeMaker` with the `Run2_UL` branch, I find weird behavior when the `HiddenSectorProducer` is run. Seemingly pseudo-randomly, the producer encounters an InvalidID exception. An example exception message that occurred after successfully running on 36k events in the same ROOT file is shown below. Thus far, I have observed this to occur for 2016 and 2018 POWHEG ttbar files (only samples tested with).

```
----- Begin Fatal Exception 22-Dec-2021 15:31:49 UTC-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing  Event run: 1 lumi: 87331 event: 87330791 stream: 0
   [1] Running path 'WriteTree'
   [2] Prefetching for module TreeMaker/'TreeMaker2'
   [3] Calling method for module HiddenSectorProducer/'HiddenSector'
Exception Message:
InvalidID get by product ID: invalid ProductID supplied
   Additional Info:
      [a] If you wish to continue processing events after a ProductNotFound exception,
add "SkipEvent = cms.untracked.vstring('ProductNotFound')" to the "options" PSet in the configuration.

----- End Fatal Exception -------------------------------------------------
22-Dec-2021 15:31:49 UTC  Closed file root://cmsxrootd.fnal.gov//store/mc/RunIISummer20UL16MiniAODv2/TTToHadronic_TuneCP5_13TeV-powheg-pythia8/MINIAODSIM/106X_mcRun2_asymptotic_v17-v1/70000/0E17501A-465E-1D4F-970C-A44B4FAB86E0.root
```

**Comment by kpedro88** [comment]
This is an unfortunately not very useful error message.

Does it really happen randomly, not on a specific event? Or does it just look that way because of e.g. running multithreaded?

If it's really random, then we need to run valgrind to check for memory corruption.

**Comment by JHiltbrand** [comment]
I looked into one of the files that was being processed (different than example above) when the exception occurred, and `TreeMaker` will consistently encounter the same exception on the same event. For instance with this dilepton ttbar file [1]. The above exception is encountered on record 470.

[1] root://cmsxrootd.fnal.gov//store/mc/RunIISummer20UL16MiniAODv2/TTTo2L2Nu_TuneCP5_13TeV-powheg-pythia8/MINIAODSIM/106X_mcRun2_asymptotic_v17-v1/120000/038D9F5E-C340-FD45-B613-DD495181C237.root

**Comment by kpedro88** [comment]
Excellent, a deterministic bug is much easier to locate.

Here's the trace I got:
```
#0  __cxxabiv1::__cxa_throw (obj=0x7fffa3c7dd00, tinfo=0x7ffff78a6fc8 <typeinfo for edm::Exception>, dest=0x7ffff7858690 <edm::Exception::~Exception()>)
    at ../../../../libstdc++-v3/libsupc++/eh_throw.cc:76
#1  0x00007ffff7d145d4 in edm::EventPrincipal::pidToBid(edm::ProductID const&) const ()
   from /cvmfs/cms.cern.ch/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_6_29/lib/slc7_amd64_gcc700/libFWCoreFramework.so
#2  0x00007ffff7d147e3 in edm::EventPrincipal::getByProductID(edm::ProductID const&) const ()
   from /cvmfs/cms.cern.ch/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_6_29/lib/slc7_amd64_gcc700/libFWCoreFramework.so
#3  0x00007ffff7d14b88 in edm::EventPrincipal::getIt(edm::ProductID const&) const ()
   from /cvmfs/cms.cern.ch/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_6_29/lib/slc7_amd64_gcc700/libFWCoreFramework.so
#4  0x00007fffee89ecbd in edm::Ptr<reco::Candidate>::getData_ (throwIfNotFound=true, this=0x7fffd2915070)
    at /cvmfs/cms.cern.ch/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_6_29/src/DataFormats/Common/interface/Ptr.h:205
#5  edm::Ptr<reco::Candidate>::operator* (this=0x7fffd2915070)
    at /cvmfs/cms.cern.ch/slc7_amd64_gcc700/cms/cmssw/CMSSW_10_6_29/src/DataFormats/Common/interface/Ptr.h:242
#6  reco::CompositePtrCandidate::daughter (this=<optimized out>, i=<optimized out>)
    at /uscms_data/d3/pedrok/SUSY2015/upgrade/forUL/new2/CMSSW_10_6_29/src/DataFormats/Candidate/src/CompositePtrCandidate.cc:14
#7  0x00007fffc2b083d8 in HiddenSectorProducer::checkLast (this=this@entry=0x7fffc8490800, jet=..., stableDs=std::unordered_set with 0 elements, 
    value=value@entry=1, frac=@0x7fffffff39d0: 0)
    at /uscms_data/d3/pedrok/SUSY2015/upgrade/forUL/new2/CMSSW_10_6_29/src/TreeMaker/Utils/src/HiddenSectorProducer.cc:150
#8  0x00007fffc2b0d253 in HiddenSectorProducer::produce (this=0x7fffc8490800, iEvent=..., iSetup=...)
    at /uscms_data/d3/pedrok/SUSY2015/upgrade/forUL/new2/CMSSW_10_6_29/src/TreeMaker/Utils/src/HiddenSectorProducer.cc:374
```

It appears that one of the GenJet constituent GenParticles was not stored in the miniAOD. I'm not sure why that would occur. However, the GenJet-dependent algorithms in HiddenSectorProducer really only need to be run on SVJ signal samples, so I'll just disable them for non-signal samples. (If we still encounter this issue on signal samples, we'll have to debug it further then, or implement workarounds.)

**Comment by kpedro88** [comment]
see #602
